[tool.isort]
# Black compatible values for isort https://black.readthedocs.io/en/stable/compatible_configs.html#isort
profile = "black"

[tool.pytest.ini_options]
addopts = "-v"

[tool.coverage.report]
omit = ["eis_qgis_plugin/qgis_plugin_tools/*"]
