[resample]
name = "resample_raster"
display_name = "Resample"
group = "Raster Processing Tools"
group_id = "raster_processing_tools"
short_help = "Resample raster to new resolution"

    [resample.parameter_1]
    name = "input_raster"
    type = "raster"
    description = "Input raster"

    [resample.parameter_2]
    name = "resampling_method"
    type = "enum"
    description = "Resampling method"
    options = "Nearest | Bilinear | Cubic | Average | Gauss | Max | Min"

    [resample.parameter_3]
    name = "upscale_factor"
    type = "number"
    description = "Upscale factor"
    num_type = "double"

    [resample.parameter_4]
    name = "output_raster"
    type = "raster_out"
    description = "Output raster"

[reproject]
name = "reproject_raster"
display_name = "Reproject"
group = "Raster Processing Tools"
group_id = "raster_processing_tools"
short_help = "Reproject raster to a new coordinate reference system"

    [reproject.parameter_1]
    name = "input_raster"
    type = "raster"
    description = "Input raster"

    [reproject.parameter_2]
    name = "CRS"
    type = "crs"
    description = "Target CRS"

    [reproject.parameter_3]
    name = "resampling_method"
    type = "enum"
    description = "Resampling method"
    options = "Nearest | Bilinear | Cubic | Average | Gauss | Max | Min"

[clip]
name = "clip_raster"
display_name = "Clip raster"
group = "Raster Processing Tools"
group_id = "raster_processing_tools"
short_help = "Clip raster with the input polygon layer"

    [snap.parameter_1]
    name = "input_raster"
    type = "raster"
    description = "Input raster"

    [snap.parameter_2]
    name = "geometries"
    type = "vector"
    description = "Areas to be clipped"
