# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_box_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class UiDialog:
    def setupUi(self, dialog):
        dialog.setObjectName("Dialog")
        dialog.resize(640, 792)
        self.scrollArea = QtWidgets.QScrollArea(dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 611, 591))
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.scrollArea.size_policy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(size_policy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setEnabled(True)
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 609, 589))
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(
            self.scrollAreaWidgetContents_4.size_policy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents_4.setSizePolicy(size_policy)
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 571, 491))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_20 = QtWidgets.QLabel(self.groupBox_10)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 441, 81))
        self.label_20.setStyleSheet('font: italic 11pt "Ubuntu";')
        self.label_20.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_20.setGeometry(QtCore.QRect(460, 80, 89, 25))
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 441, 81))
        self.label_21.setStyleSheet('font: italic 11pt "Ubuntu";')
        self.label_21.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_21.setGeometry(QtCore.QRect(460, 80, 89, 25))
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBox_12.setFlat(False)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 441, 81))
        self.label_22.setStyleSheet('font: italic 11pt "Ubuntu";')
        self.label_22.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_22.setGeometry(QtCore.QRect(460, 80, 89, 25))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_10.setTitle(_translate("Dialog", "Reclassify"))
        self.label_20.setText(
            _translate(
                "Dialog",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper suscipit tortor, ac sagittis nibh cursus vel. Pellentesque nec sem nec lectus vulputate sodales ut in odio. Nullam nec tincidunt diam, vitae finibus purus. Sed rutrum malesuada odio, in imperdiet tortor commodo eu. ",
            )
        )
        self.pushButton_20.setText(_translate("Dialog", "Run"))
        self.groupBox_11.setTitle(_translate("Dialog", "Reclassify"))
        self.label_21.setText(
            _translate(
                "Dialog",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper suscipit tortor, ac sagittis nibh cursus vel. Pellentesque nec sem nec lectus vulputate sodales ut in odio. Nullam nec tincidunt diam, vitae finibus purus. Sed rutrum malesuada odio, in imperdiet tortor commodo eu. ",
            )
        )
        self.pushButton_21.setText(_translate("Dialog", "Run"))
        self.groupBox_12.setTitle(_translate("Dialog", "Reclassify"))
        self.label_22.setText(
            _translate(
                "Dialog",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper suscipit tortor, ac sagittis nibh cursus vel. Pellentesque nec sem nec lectus vulputate sodales ut in odio. Nullam nec tincidunt diam, vitae finibus purus. Sed rutrum malesuada odio, in imperdiet tortor commodo eu. ",
            )
        )
        self.pushButton_22.setText(_translate("Dialog", "Run"))
